# Generated by Django 5.0.3 on 2025-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_imfverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imfverification',
            name='imf_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
