# Generated by Django 5.0.3 on 2025-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_imfverification_imf_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transaction_info',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Completed', max_length=10),
        ),
    ]
