# Generated by Django 5.0.3 on 2025-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_transfer_transaction_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transaction_info',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
