# Generated by Django 5.0.3 on 2025-03-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_profile_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='account_number',
            field=models.CharField(max_length=15),
        ),
    ]
