# Generated by Django 5.0.3 on 2025-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_transfer_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='message',
            field=models.CharField(max_length=999),
        ),
    ]
