# Generated by Django 5.0.3 on 2025-03-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_chatbox_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='holder_name',
            field=models.CharField(default='account_user', max_length=250),
            preserve_default=False,
        ),
    ]
