# Generated by Django 5.0.3 on 2025-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_transfer_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
    ]
