# Generated by Django 5.0.3 on 2025-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_chatbox_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='message_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='chat_images'),
        ),
    ]
