# Generated by Django 5.0.3 on 2025-04-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_chatbox_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='message',
            field=models.CharField(default='', max_length=999),
        ),
    ]
