# Generated by Django 5.0.3 on 2025-04-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_chatbox_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='message',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='chatbox',
            name='message_image',
            field=models.ImageField(default='default.jpg', upload_to='chat_images'),
        ),
    ]
