# Generated by Django 5.0.3 on 2025-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_chatbox_message_alter_chatbox_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='message_image',
            field=models.ImageField(blank=True, upload_to='chat_images'),
        ),
    ]
